// generated by newgenasym  Fri Jul 16 11:27:52 2021


module oled (cs, dc, gnd, res, scl, sda, vcc);
    inout cs;
    inout dc;
    inout gnd;
    inout res;
    inout scl;
    inout sda;
    inout vcc;


    initial
        begin
        end

endmodule
