// generated by newgenasym  Wed Jul 14 14:18:45 2021


module oled (cs, d0, d1, dc, gnd, res, vcc);
    inout cs;
    inout d0;
    inout d1;
    inout dc;
    inout gnd;
    inout res;
    inout vcc;


    initial
        begin
        end

endmodule
