-- generated by newgenasym Wed Jul 14 14:18:45 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity oled is
    port (    
	CS:        INOUT  STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	DC:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RES:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end oled;
