-- generated by newgenasym Fri Jul 16 11:57:50 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bjt_pnp is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end bjt_pnp;
