-- generated by newgenasym Thu Jul 15 19:13:43 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mlx90614 is
    port (    
	GND:       OUT    STD_LOGIC;    
	SCL:       OUT    STD_LOGIC;    
	SDA:       OUT    STD_LOGIC;    
	VCC:       OUT    STD_LOGIC);
end mlx90614;
