// generated by newgenasym  Wed Jul 14 18:12:00 2021


module switcher (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
