-- generated by newgenasym Wed Jul 14 18:12:00 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity switcher is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end switcher;
