// generated by newgenasym  Thu Jul 15 13:45:59 2021


module switch (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
