-- generated by newgenasym Wed Jul 14 19:38:27 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm358 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\ina+\:    INOUT  STD_LOGIC;    
	\ina-\:    INOUT  STD_LOGIC;    
	\inb+\:    INOUT  STD_LOGIC;    
	\inb-\:    INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end lm358;
