-- generated by newgenasym Tue Jul 13 15:28:40 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end crystal;
