-- generated by newgenasym Wed Jul 14 18:10:13 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end crystal;
