// generated by newgenasym  Wed Jul 14 19:38:27 2021


module lm339 (gnd, \in+(1) , \in+(2) , \in+(3) , \in+(4) , \in-(1) , \in-(2) , \in-(3) ,
        \in-(4) , out1, out2, out3, out4, vcc);
    inout gnd;
    inout \in+(1) ;
    inout \in+(2) ;
    inout \in+(3) ;
    inout \in+(4) ;
    inout \in-(1) ;
    inout \in-(2) ;
    inout \in-(3) ;
    inout \in-(4) ;
    inout out1;
    inout out2;
    inout out3;
    inout out4;
    inout vcc;


    initial
        begin
        end

endmodule
