// generated by newgenasym  Wed Jul 14 23:31:58 2021


module socket5 (\+5v , \3v3 , gnd, rxd, txd);
    inout \+5v ;
    inout \3v3 ;
    inout gnd;
    inout rxd;
    inout txd;


    initial
        begin
        end

endmodule
