-- generated by newgenasym Wed Jul 14 23:31:58 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity socket5 is
    port (    
	\+5v\:     INOUT  STD_LOGIC;    
	\3v3\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC);
end socket5;
