// generated by newgenasym  Wed Jul 14 16:07:14 2021


module l7805 (\1/input , \2/gnd , \3/ouput );
    inout \1/input ;
    inout \2/gnd ;
    inout \3/ouput ;


    initial
        begin
        end

endmodule
