-- generated by newgenasym Wed Jul 14 16:07:14 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l7805 is
    port (    
	\1/input\: INOUT  STD_LOGIC;    
	\2/gnd\:   INOUT  STD_LOGIC;    
	\3/ouput\: INOUT  STD_LOGIC);
end l7805;
