-- generated by newgenasym Wed Jul 14 19:38:27 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm339 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in+(1)\:  INOUT  STD_LOGIC;    
	\in+(2)\:  INOUT  STD_LOGIC;    
	\in+(3)\:  INOUT  STD_LOGIC;    
	\in+(4)\:  INOUT  STD_LOGIC;    
	\in-(1)\:  INOUT  STD_LOGIC;    
	\in-(2)\:  INOUT  STD_LOGIC;    
	\in-(3)\:  INOUT  STD_LOGIC;    
	\in-(4)\:  INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC;    
	OUT4:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end lm339;
