// generated by newgenasym  Thu Jul 15 19:13:43 2021


module mlx90614 (gnd, scl, sda, vcc);
    output gnd;
    output scl;
    output sda;
    output vcc;


    initial
        begin
        end

endmodule
