// generated by newgenasym  Tue Jul 13 19:02:19 2021


module mlx90614 (\scl/vz , \sda/pwm , vdd, vss);
    inout \scl/vz ;
    input \sda/pwm ;
    input vdd;
    input vss;


    initial
        begin
        end

endmodule
