// generated by newgenasym  Thu Jul 15 14:23:20 2021


module mlx90614 (\scl/vz , \sda/pwm , vdd, vss);
    output \scl/vz ;
    output \sda/pwm ;
    input vdd;
    input vss;


    initial
        begin
        end

endmodule
