-- generated by newgenasym Thu Jul 15 14:23:20 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mlx90614 is
    port (    
	\scl/vz\:  OUT    STD_LOGIC;    
	\sda/pwm\: OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC);
end mlx90614;
