-- generated by newgenasym Wed Jul 14 18:10:46 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mlx90614 is
    port (    
	\scl/vz\:  INOUT  STD_LOGIC;    
	\sda/pwm\: IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC);
end mlx90614;
