-- generated by newgenasym Thu Jul 15 16:10:37 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity buzz is
    port (    
	\+\:       INOUT  STD_LOGIC;    
	\-\:       INOUT  STD_LOGIC);
end buzz;
