// generated by newgenasym  Thu Jul 15 20:13:24 2021


module socket6 (en, gnd, rxd, state, txd, vcc);
    inout en;
    inout gnd;
    inout rxd;
    inout state;
    inout txd;
    inout vcc;


    initial
        begin
        end

endmodule
