-- generated by newgenasym Thu Jul 15 20:13:24 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity socket6 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	STATE:     INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end socket6;
