-- generated by newgenasym Thu Jul 15 13:15:42 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity socket2 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC);
end socket2;
