// generated by newgenasym  Thu Jul 15 19:04:37 2021


module socket5 (\+5v , \3v3 , gnd, rxd, txd);
    inout \+5v ;
    inout \3v3 ;
    inout gnd;
    inout rxd;
    inout txd;


    initial
        begin
        end

endmodule
