// generated by newgenasym  Fri Jul 16 11:24:38 2021


module lcd1602 (bla, blk, d0, d1, d2, d3, d4, d5, d6, d7, e, gnd, \r/w , rs, vcc, vl);
    inout bla;
    inout blk;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout e;
    inout gnd;
    inout \r/w ;
    inout rs;
    inout vcc;
    inout vl;


    initial
        begin
        end

endmodule
