-- generated by newgenasym Wed Jul 14 10:34:15 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity resistor is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end resistor;
