-- generated by newgenasym Thu Jul 15 13:45:59 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity switch is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end switch;
