// generated by newgenasym  Wed Jul 14 23:32:01 2021


module socket6 (en, gnd, rxd, state, txd, vcc);
    inout en;
    inout gnd;
    inout rxd;
    inout state;
    inout txd;
    inout vcc;


    initial
        begin
        end

endmodule
