-- generated by newgenasym Fri Jul 16 11:27:52 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity oled is
    port (    
	CS:        INOUT  STD_LOGIC;    
	DC:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RES:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end oled;
