-- generated by newgenasym Wed Jul 14 19:38:27 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity potentiometer is
    port (    
	CCW:       INOUT  STD_LOGIC;    
	CW:        INOUT  STD_LOGIC;    
	WIPER:     INOUT  STD_LOGIC);
end potentiometer;
