// generated by newgenasym  Fri Jul 16 10:21:26 2021


module at24c02 (a0, a1, a2, gnd, scl, sda, vcc, wp);
    inout a0;
    inout a1;
    inout a2;
    inout gnd;
    inout scl;
    inout sda;
    inout vcc;
    inout wp;


    initial
        begin
        end

endmodule
