-- generated by newgenasym Fri Jul 16 10:21:26 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity at24c02 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	WP:        INOUT  STD_LOGIC);
end at24c02;
