-- generated by newgenasym Thu Jul 15 13:45:50 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity capacitance is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end capacitance;
