// generated by newgenasym  Wed Jul 14 19:38:27 2021


module lm358 (gnd, \ina+ , \ina- , \inb+ , \inb- , outa, outb, vcc);
    inout gnd;
    inout \ina+ ;
    inout \ina- ;
    inout \inb+ ;
    inout \inb- ;
    inout outa;
    inout outb;
    inout vcc;


    initial
        begin
        end

endmodule
